### PR TITLE
Fix acceptance and rejection logic

### LINKED ISSUE #17: Solution inconsistent with vanilla OrdinaryDiffEq.jl
**Describe the bug 🐞**

When solving a simple decaying exponential ODE, the solution output by this package is inconsistent with the solution provided by OrdinaryDiffEq.jl. To be specific, most time points are identical, except for a few time points where the solution output from this package is the initial condition (within numerical precision, at least).

**Minimal Reproducible Example 👇**

```julia
using OrdinaryDiffEqLowOrderRK
using OrdinaryDiffEqOperatorSplitting

function OrdinaryDiffEqOperatorSplitting.synchronize_solution_with_parameters!(
    ::OrdinaryDiffEqOperatorSplitting.OperatorSplittingIntegrator, ::Vector{T}, _
) where {T<:Number} end

f(du, u, p, t) = @. du = -u + p
tspan = (0.0, 2.0)
u0 = [1.0]
p = [0.9]
dt = 0.1

cell_indices = 1:1
split_f = GenericSplitFunction((f,), (cell_indices,))
prob = OperatorSplittingProblem(split_f, u0, tspan, (p,); alias_u0=false)
splitting_solver = LieTrotterGodunov((Euler(),))

println("\nSolving with OperatorSplittingProblem")
integrator = init(prob, splitting_solver; dt=dt)
for (u, t) in TimeChoiceIterator(integrator, tspan[1]:(2dt):tspan[2])
    @show u
end

##

println("\nSolving with ODEProblem")
prob = ODEProblem(f, u0, tspan, p)
integrator = init(prob, Euler(); dt=dt)
for (u, t) in TimeChoiceIterator(integrator, tspan[1]:(2dt):tspan[2])
    @show u
end
```

Output:

```julia
Solving with OperatorSplittingProblem
u = [1.0]
u = [0.981]
u = [0.96561]
u = [0.9531440999999999]
u = [0.9999999999999999]
u = [0.9999999999999999]
u = [0.9282429536480999]
u = [0.922876792454961]
u = [0.9185302018885184]
u = [0.9150094635297001]
u = [0.9121576654590569]

Solving with ODEProblem
u = [1.0]
u = [0.981]
u = [0.96561]
u = [0.9531440999999999]
u = [0.943046721]
u = [0.93486784401]
u = [0.9282429536480999]
u = [0.9228767924549609]
u = [0.9185302018885183]
u = [0.9150094635296998]
u = [0.9121576654590569]
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `/tmp/jl_K2G0Dm/Project.toml`
  [1344f307] OrdinaryDiffEqLowOrderRK v1.2.0
  [760fc936] OrdinaryDiffEqOperatorSplitting v0.2.0 `https://github.com/SciML/OrdinaryDiffEqOperatorSplitting.jl#main`
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `/tmp/jl_K2G0Dm/Manifest.toml`
  [47edcb42] ADTypes v1.15.0
  [7d9f7c33] Accessors v0.1.42
  [79e6a3ab] Adapt v4.3.0
  [4fba245c] ArrayInterface v7.19.0
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [2a0fbf3d] CPUSummary v0.2.6
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [38540f10] CommonSolve v0.2.4
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.17.0
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.6.0
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.22
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.178.0
  [ffbed154] DocStringExtensions v0.9.5
  [4e289a0a] EnumX v1.0.5
  [f151be2c] EnzymeCore v0.8.12
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [a4df4552] FastPower v1.1.3
  [1a297f60] FillArrays v1.13.0
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [46192b85] GPUArraysCore v0.2.0
  [615f187c] IfElse v0.1.1
  [3587e190] InverseFunctions v0.1.17
  [82899510] IteratorInterfaceExtensions v1.0.0
  [ae98c720] Jieko v0.2.1
  [b964fa9f] LaTeXStrings v1.4.0
  [10f19ff3] LayoutPointers v0.1.17
  [1914dd2f] MacroTools v0.5.16
  [d125e4d3] ManualMemory v0.1.8
  [2e0e35c7] Moshi v0.3.7
  [46d2c3a1] MuladdMacro v0.2.4
  [bac558e1] OrderedCollections v1.8.1
  [bbf590c4] OrdinaryDiffEqCore v1.26.2
  [1344f307] OrdinaryDiffEqLowOrderRK v1.2.0
  [760fc936] OrdinaryDiffEqOperatorSplitting v0.2.0 `https://github.com/SciML/OrdinaryDiffEqOperatorSplitting.jl#main`
  [d96e819e] Parameters v0.12.3
  [f517fe37] Polyester v0.7.18
  [1d0040c9] PolyesterWeave v0.2.2
⌅ [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [08abe8d2] PrettyTables v2.4.0
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.35.0
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.1
  [7e49a35a] RuntimeGeneratedFunctions v0.5.15
  [94e857df] SIMDTypes v0.1.0
  [0bca4576] SciMLBase v2.104.0
  [c0aeaf25] SciMLOperators v1.3.1
  [53ae85a6] SciMLStructures v1.7.0
  [efcf1570] Setfield v1.1.2
  [ce78b400] SimpleUnPack v1.1.0
  [aedffcd0] Static v1.2.0
  [0d7ed370] StaticArrayInterface v1.8.0
  [1e83bf80] StaticArraysCore v1.4.3
  [10745b16] Statistics v1.11.1
  [7792a7ef] StrideArraysCore v0.5.7
  [892a3eda] StringManipulation v0.4.1
  [2efcf032] SymbolicIndexingInterface v0.3.42
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.1
  [8290d209] ThreadingUtilities v0.5.5
  [a759f4b9] TimerOutputs v0.5.29
  [781d530d] TruncatedStacktraces v1.4.0
  [3a884ed6] UnPack v1.0.2
  [9602ed7d] Unrolled v0.1.5
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [6462fe0b] Sockets v1.11.0
  [fa267f1f] TOML v1.0.3
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [4536629a] OpenBLAS_jll v0.3.27+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
Julia Version 1.11.6
Commit 9615af0f269 (2025-07-09 12:58 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 9900X 12-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, generic)
Threads: 20 default, 0 interactive, 10 GC (on 24 virtual cores)
Environment:
  LD_PRELOAD = /usr/lib/x86_64-linux-gnu/libstdc++.so.6
  JULIA_NUM_THREADS = 20
```

### PR DESCRIPTION
**Pull request by termi-official**
Resolves #17

### CODE REVIEW

**Review by kylebeggs — COMMENTED** [review]
There is a lot here that I'm not sure is related to the issue? Why do we need `IntegratorOptions` and all the tstop handling?

**Comment by kylebeggs** [comment]
@oscardssmith can you look at this soon or should we merge to squash the bug? I know we can just point to use this branch as a dep, but I believe bug fixes should be merged ASAP so I don't want to just leave this bug on main for a while.

File: src/integrator.jl [hunk 1]
```diff
@@ -376,37 +624,37 @@ function DiffEqBase.postamble!(integrator::OperatorSplittingIntegrator)
...
-    integrator.tprev = integrator.t
-    integrator.t = !isempty(tstops) && abs(first(tstops) - tnext) < max_t_error ? first(tstops) : tnext
+    # # Update integrator
+    # # increment t by dt, rounding to the first tstop if that is roughly
+    # # equivalent up to machine precision; the specific bound of 100 * eps...
+    # # is taken from OrdinaryDiffEq.jl
+    # t_unit = oneunit(integrator.t)
+    # max_t_error = 100 * eps(float(integrator.t / t_unit)) * t_unit
+    # integrator.tprev = integrator.t
+    # integrator.t = !isempty(tstops) && abs(first(tstops) - tnext) < max_t_error ? first(tstops) : tnext
```
Comment (oscardssmith) [inline src/integrator.jl:650]: delete this. Commented out code shouldn't exist.

**Comment by termi-official** [comment]
Thanks for taking time @oscardssmith . If you give green light, then @kylebeggs can merge.
