### PR TITLE
change default alias_u0=false

### LINKED ISSUE #13: Initial condition is mutated
**Describe the bug 🐞**

`OperatorSplittingProblem` modifies the initial condition. The rest fo the ecosystem does not do this and I believe that is intentional, making this a bug.

**Expected behavior**

the supplied initial condition is copied and thus not mutated

**Minimal Reproducible Example 👇**

```julia
using OrdinaryDiffEqOperatorSplitting
using OrdinaryDiffEq

# This is the first operator of the ODE.
function ode1(du, u, p, t)
    @. du = -0.1u
end
f1 = ODEFunction(ode1)
f1dofs = [1, 2, 3]

# This is the second operator of the ODE.
function ode2(du, u, p, t)
    du[1] = -0.01u[2]
    du[2] = -0.01u[1]
end
f2 = ODEFunction(ode2)
f2dofs = [1, 3]

# This defines the split of the ODE.
f = GenericSplitFunction((f1, f2), (f1dofs, f2dofs))

# Next we can define the split problem.
u0 = [-1.0, 1.0, 0.0]
tspan = (0.0, 1.0)
prob = OperatorSplittingProblem(f, u0, tspan)

# And the time integration algorithm.
alg = LieTrotterGodunov((Euler(), Euler()))

# Right now OrdinaryDiffEqOperatorSplitting.jl does not implement the SciML solution interface,
# but we can only intermediate solutions via the iterator interface.
integrator = init(prob, alg; dt=0.1)
for (u, t) in TimeChoiceIterator(integrator, 0.0:0.5:1.0)
    @show t, u
end

display(u0)

#=
3-element Vector{Float64}:
 -0.9044227723921003
  0.9043820750088045
  0.009043929276164951
=#
```

Just wanted to double check this should be classified as bug before submitting a PR.

### PR DESCRIPTION
**Pull request by kylebeggs**
title. closes #13

### CODE REVIEW

File: src/integrator.jl [hunk 1]
```diff
@@ -494,7 +494,7 @@ function build_subintegrator_tree_with_cache(
 
     # TODO fix mixed device type problems we have to be smarter
     return subintegrator_tree, init_cache(f, alg;
-        uprev=uprevouter, u=uouter, alias_u=true,
+        uprev=uprevouter, u=uouter, alias_u=false,
```
Comment (oscardssmith) [inline src/integrator.jl:497]: shouldn't this be `alias_u=alias_u0`?

Comment (kylebeggs) [reply src/integrator.jl:497]: Yeah, I think we should we propagating `alias_u0` down and doing this. Sanity check @termi-official ?

Comment (termi-official) [reply src/integrator.jl:497]: This one here is a bit trickier, as it is independent of how u0 is treated. https://github.com/SciML/OrdinaryDiffEqOperatorSplitting.jl/blob/650ca71e9ab04ca3b3b760787aaa5311e991b6da/src/solver.jl#L24-L25

Comment (kylebeggs) [reply src/integrator.jl:497]: I see. actually, I think we should leave this as it was before because of:
https://github.com/SciML/OrdinaryDiffEqOperatorSplitting.jl/blob/main/src/integrator.jl#L90

**Comment by kylebeggs** [comment]
I think this is relatively straight-forward. can someone approve?

**Review by termi-official — APPROVED** [review]
LGTM. Thanks for taking care Kyle!
